#!/usr/bin/env bash

# source bash profile to get environment variables set
if [ -z "$USER_PROFILE_LOADED"] && [ -f "$HOME/.bash_profile" ]; then
  source "$HOME/.bash_profile"
fi

# tell the script to exit with failure if any command
# returns a non-zero exit code
set -e

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
USER_DOTFILES=$(pwd -P)

#---------------------------------------------------------------------
# Projects.  The list of supported projects comes from
# https://github.com/daptiv/dotfiles/tree/master/projects/
# Each folder name is a project.  Just include the folder name as
# outlined below, to include that project in your setup.
#---------------------------------------------------------------------
echo "Configuring projects"
SETUP_SCRIPT="$HOME/.daptiv-dotfiles/projects/setup"
if [ -f "$SETUP_SCRIPT" ]; then
  # you can comment out any project you don't wish to include by putting a # at the beginning of the line
  # bash "$SETUP_SCRIPT" cognos
  # bash "$SETUP_SCRIPT" dtb
  bash "$SETUP_SCRIPT" new-feature-popup
  bash "$SETUP_SCRIPT" portainer
  # bash "$SETUP_SCRIPT" react-theme
  # bash "$SETUP_SCRIPT" ttm
  echo "Finished configuring projects"
fi

#---------------------------------------------------------------------
# Personal setup
# If you have another personal repository that has additional
# configuration, such as license keys, you can call out to it here.
#---------------------------------------------------------------------
# personal="$HOME/src/personal-configuration/setup.sh"
#[ -f "$personal" ] && bash "$personal"

# TODO
# open '/usr/local/Caskroom/lastpass/latest/LastPass Installer/LastPass Installer.app'
# smart switch?
# waterfox?

# Require login to App Store
set +e
mas account > /dev/null
EXITCODE=$?
set -e
if [ $EXITCODE != 0 ]; then
  echo
  echo -e "\e[92mLog into the App Store!\e[0m"
  echo Then press a key to continue...
  read -sn 1
fi

# Re-install App Store apps
# 1295203466 = MS Remote Desktop
# 967004861  = HP Easy Scan
# 926036361  = LastPass
# 905264208  = Disk Cartography
mas install 1295203466 967004861 926036361 905264208

# Customize dock
pushd $USER_DOTFILES/customization/dock
npm install -g yarn
yarn install
yarn start
popd

$USER_DOTFILES/customization/.macos

# Link p4merge
mkdir -p -m u=rwx,g=,o= ~/bin
ln -fs ~/.dotfiles/files/p4merge ~/bin/p4merge

# Copy p4merge config
P4MERGE_SETTINGS="$HOME/Library/Preferences/com.perforce.p4merge"
mkdir -p $P4MERGE_SETTINGS
cp "$USER_DOTFILES/customization/p4merge/ApplicationSettings.xml" "$P4MERGE_SETTINGS"

# Config git
git config --global alias.dt difftool
git config --global alias.mt mergetool
git config --global core.editor "code -nw"
git config --global core.excludesfile "~/.dotfiles/files/gitignore"
git config --global hub.protocol https
git config --global merge.tool p4merge
git config --global mergetool.keepTemporaries false
git config --global mergetool.prompt false

# Add newer bash to allowed shells
NEWBASH=/usr/local/bin/bash
!(grep -q "$NEWBASH" /etc/shells) && echo $NEWBASH | sudo tee -a /etc/shells > /dev/null

# Set newer bash as default
if [ "$SHELL" != "$NEWBASH" ]; then sudo chsh -s $NEWBASH $USER; fi
